using Planora.Domain.Entities;
using System.Text.Json;

namespace Planora.Persistence.SeedData;

public static class SeedTestData
{
    public static List<School> SetSeedDataSchool() => new List<School>
    {
        new School { Name = "Osman İlköğretim" }
    };
    public static List<SchoolScheduleSetting> SetSeedDataSchoolchoolScheduleSetting() => new List<SchoolScheduleSetting>
    {
        new SchoolScheduleSetting {FirstLessonStartTime = TimeSpan.Parse("07:00:00"), LessonDurationMinutes = 40, BreakDurationMinutes = 15, DailyLessonCount = 8 , WeeklyLessonDayCount=5}
    };
    public static List<LectureDistributionOption> SetSeedDataLectureDistributionOption()
    {
        return new List<LectureDistributionOption>
        {
            new() { TotalHours = 1, Distribution = JsonSerializer.Serialize(new List<int> { 1 }) },
            new() { TotalHours = 2, Distribution = JsonSerializer.Serialize(new List<int> { 2 }) },
            new() { TotalHours = 3, Distribution = JsonSerializer.Serialize(new List<int> { 2, 1 }) },
            new() { TotalHours = 4, Distribution = JsonSerializer.Serialize(new List<int> { 2, 2 }) },
            new() { TotalHours = 5, Distribution = JsonSerializer.Serialize(new List<int> { 3, 2 }) },
            new() { TotalHours = 6, Distribution = JsonSerializer.Serialize(new List<int> { 3, 3 }) },
            new() { TotalHours = 7, Distribution = JsonSerializer.Serialize(new List<int> { 4, 2, 1 }) },
            new() { TotalHours = 8, Distribution = JsonSerializer.Serialize(new List<int> { 4, 4 }) },
            new() { TotalHours = 9, Distribution = JsonSerializer.Serialize(new List<int> { 3, 3, 3 }) },
            new() { TotalHours = 10, Distribution = JsonSerializer.Serialize(new List<int> { 4, 4, 2 }) },
            new() { TotalHours = 11, Distribution = JsonSerializer.Serialize(new List<int> { 4, 4, 3 }) }, 
            new() { TotalHours = 12, Distribution = JsonSerializer.Serialize(new List<int> { 4, 4, 4 }) },
            new() { TotalHours = 13, Distribution = JsonSerializer.Serialize(new List<int> { 5, 4, 4 }) }, 
            new() { TotalHours = 14, Distribution = JsonSerializer.Serialize(new List<int> { 5, 5, 4 }) }, 
            new() { TotalHours = 15, Distribution = JsonSerializer.Serialize(new List<int> { 5, 5, 5 }) }, 
            new() { TotalHours = 16, Distribution = JsonSerializer.Serialize(new List<int> { 4, 4, 4, 4 }) }
        };
    }

    //public static List<ClassSection> SetSeedDataClassSection() => new List<ClassSection>
    //{
    //    new ClassSection{FakeId=1,  Name="9-A"},
    //    new ClassSection{FakeId=2,  Name="9-B"},
    //    new ClassSection{FakeId=3,  Name="9-C"},
    //    new ClassSection{FakeId=4,  Name="9-D"},
    //    new ClassSection{FakeId=5,  Name="9-E"},
    //    new ClassSection{FakeId=6,  Name="10-A"},
    //    new ClassSection{FakeId=7,  Name="10-B"},
    //    new ClassSection{FakeId=8,  Name="10-C"},
    //    new ClassSection{FakeId=9,  Name="10-D"},
    //    new ClassSection{FakeId=10, Name="10-E"},
    //    new ClassSection{FakeId=11, Name="11-A"},
    //    new ClassSection{FakeId=12, Name="11-B"},
    //    new ClassSection{FakeId=13, Name="11-C"},
    //    new ClassSection{FakeId=14, Name="11-D"},
    //    new ClassSection{FakeId=15, Name="11-E"},
    //    new ClassSection{FakeId=16, Name="11-F TM"},
    //    new ClassSection{FakeId=17, Name="11-G TM"},
    //    new ClassSection{FakeId=18, Name="11-H DİL"},
    //    new ClassSection{FakeId=19, Name="12-A"},
    //    new ClassSection{FakeId=20, Name="12-B"},
    //    new ClassSection{FakeId=21, Name="12-C"},
    //    new ClassSection{FakeId=22, Name="12-D"},
    //    new ClassSection{FakeId=23, Name="12-E TM"},
    //    new ClassSection{FakeId=24, Name="12-F TM"},
    //    new ClassSection{FakeId=25, Name="12-G DİL"}
    //};
    //public static List<Teacher> SetSeedDataTeacher() => new List<Teacher>
    //{
    //    new Teacher {FakeId = 1,  FullName = "SEFA ÇOKTU" },
    //    new Teacher {FakeId = 2,  FullName = "NALAN KARATAŞ" },
    //    new Teacher {FakeId = 3,  FullName = "YAKUP TURHAN" },
    //    new Teacher {FakeId = 4,  FullName = "ESRA TEKMİL" },
    //    new Teacher {FakeId = 5,  FullName = "UĞUR AĞYÜZ" },
    //    new Teacher {FakeId = 6,  FullName = "ELA ÇAĞLAYAN" },
    //    new Teacher {FakeId = 7,  FullName = "ÖZLEM ÇOBANOĞLU" },
    //    new Teacher {FakeId = 8,  FullName = "KEREM DÖŞ" },
    //    new Teacher {FakeId = 9,  FullName = "EMEL GÖKBULUT" },
    //    new Teacher {FakeId = 10, FullName = "MEHMET ARKIN" },
    //    new Teacher {FakeId = 11, FullName = "GÜLER ULUPINAR" },
    //    new Teacher {FakeId = 12, FullName = "FİLİZ ERKAN ZORLU" },
    //    new Teacher {FakeId = 13, FullName = "AYBEN ACUN" },
    //    new Teacher {FakeId = 14, FullName = "ÜNAL AKTOKA" },
    //    new Teacher {FakeId = 15, FullName = "NİL CEYHAN KARA" },
    //    new Teacher {FakeId = 16, FullName = "AHMET FATİH TAŞTAN" },
    //    new Teacher {FakeId = 17, FullName = "ÇİĞDEM DAŞTAN" },
    //    new Teacher {FakeId = 18, FullName = "NAME TASLAK" },
    //    new Teacher {FakeId = 19, FullName = "FATİH İYİGÜN" },
    //    new Teacher {FakeId = 20, FullName = "TUBA ÜSTÜN" },
    //    new Teacher {FakeId = 21, FullName = "MERAL AKKUŞ" },
    //    new Teacher {FakeId = 22, FullName = "MURTAZA OĞUZ" },
    //    new Teacher {FakeId = 23, FullName = "EMİNE ASLAN" },
    //    new Teacher {FakeId = 24, FullName = "TUĞÇE AKTAŞ" },
    //    new Teacher {FakeId = 25, FullName = "SEMA AYDIN SÜRER" },
    //    new Teacher {FakeId = 26, FullName = "SÜMEYYE PAŞO" },
    //    new Teacher {FakeId = 27, FullName = "RAMİS AKGÜL" },
    //    new Teacher {FakeId = 28, FullName = "MEHMET TAHİR ÖKSÜZ" },
    //    new Teacher {FakeId = 29, FullName = "YASEMİN ÇELİK" },
    //    new Teacher {FakeId = 30, FullName = "ÖMER FARUK" },
    //    new Teacher {FakeId = 31, FullName = "GÜLTEN KAYHAN" },
    //    new Teacher {FakeId = 32, FullName = "MUHAMMET SÜHEYL CANSIZ" },
    //    new Teacher {FakeId = 33, FullName = "SİNEM KANSU" },
    //    new Teacher {FakeId = 34, FullName = "BURCU ACAR" },
    //    new Teacher {FakeId = 35, FullName = "MÜSTECEP ŞAHİN" },
    //    new Teacher {FakeId = 36, FullName = "ÖZCAN ESER" },
    //    new Teacher {FakeId = 37, FullName = "İBRAHİM FATİH" },
    //    new Teacher {FakeId = 38, FullName = "AKIN ZORLU" },
    //    new Teacher {FakeId = 39, FullName = "HALE ŞAHİN" },
    //    new Teacher {FakeId = 40, FullName = "ERDEM ERBAY" },
    //    new Teacher {FakeId = 41, FullName = "YASİN KILINÇ" },
    //    new Teacher {FakeId = 42, FullName = "MUSTAFA DAĞLAR" }
    //};
    //public static List<Lecture> SetSeedDataLecture() => new List<Lecture>
    //{
    //    new Lecture {FakeId = 1,  Name = "BEDEN EĞİTİMİ VE SPOR" },
    //    new Lecture {FakeId = 2,  Name = "BİYOLOJİ" },
    //    new Lecture {FakeId = 3,  Name = "COĞRAFYA" },
    //    new Lecture {FakeId = 4,  Name = "DİN KÜLTÜRÜ VE AHLAK BİLGİSİ" },
    //    new Lecture {FakeId = 5,  Name = "FİZİK" },
    //    new Lecture {FakeId = 6,  Name = "GÖRSEL SANATLAR/MÜZİK" },
    //    new Lecture {FakeId = 7,  Name = "İNGİLİZCE" },
    //    new Lecture {FakeId = 8,  Name = "KİMYA" },
    //    new Lecture {FakeId = 9,  Name = "MATEMATİK" },
    //    new Lecture {FakeId = 10, Name = "REHBERLİK" },
    //    new Lecture {FakeId = 11, Name = "SAĞLIK BİLGİSİ VE TRAFİK" },
    //    new Lecture {FakeId = 12, Name = "ADABI MUAŞERET " },
    //    new Lecture {FakeId = 13, Name = "ALMANCA" },
    //    new Lecture {FakeId = 14, Name = "DÜŞÜNME EĞİTİMİ" },
    //    new Lecture {FakeId = 15, Name = "PEYGAMBERİMİZİN HAYATI" },
    //    new Lecture {FakeId = 16, Name = "TEMEL DİNİ BİLGİLER" },
    //    new Lecture {FakeId = 17, Name = "TARİH" },
    //    new Lecture {FakeId = 18, Name = "TÜRK DİLİ VE EDEBİYATI" },
    //    new Lecture {FakeId = 19, Name = "ASTRONMİ VE UZAY" },
    //    new Lecture {FakeId = 20, Name = "FELSEFE" },
    //    new Lecture {FakeId = 21, Name = "KLS AHLK MET SNT " },
    //    new Lecture {FakeId = 22, Name = "BİLGİSAYAR BİLİMİ" },
    //    new Lecture {FakeId = 23, Name = "MATEMATİK UYGULULAMALARI" },
    //    new Lecture {FakeId = 24, Name = "METİN TAHLİLERİ" },
    //    new Lecture {FakeId = 25, Name = "TÜRK KÜL.VE MED " },
    //    new Lecture {FakeId = 26, Name = "TEMEL MATEMATİK" },
    //    new Lecture {FakeId = 27, Name = " TEMEL HUKUK BİLG" },
    //    new Lecture {FakeId = 28, Name = "TÜRK SOSYAL HAYT AİLE " },
    //    new Lecture {FakeId = 29, Name = "T.C. İNKILAP TARİHİ VE ATATÜRK" },
    //    new Lecture {FakeId = 30, Name = "ÇAĞDAŞ DÜN İNKILAP TARİHİ" },
    //    new Lecture {FakeId = 31, Name = "MATEMTİK+MAT UYGULAMALARI" },
    //    new Lecture {FakeId = 32, Name = "SPOR EĞİTİMİ" },
    //    new Lecture {FakeId = 33, Name = "ÇDŞ TÜRK DNY TARİHİ" },
    //    new Lecture {FakeId = 34, Name = "GÖRSEL SANATLAR" },
    //    new Lecture {FakeId = 35, Name = "BEDEN EĞİTİMİ" }
    //};
    //public static List<TeacherUnavailable> SetSeedDataTeacherUnavailable() => new List<TeacherUnavailable>
    //{
    //    new TeacherUnavailable {TeacherFakeId = 1, DayOfWeek=1 }
    //};
    //public static List<ClassTeachingAssignment> SetSeedDataClassTeachingAssignment() => new List<ClassTeachingAssignment>
    //{

    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 1,   TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 3,   TeacherFakeId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 5,   TeacherFakeId = 5,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 7,   TeacherFakeId = 7,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 9,   TeacherFakeId = 9,     WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 10,  TeacherFakeId = 9,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 11,  TeacherFakeId = 10,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 12,  TeacherFakeId = 7,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 14,  TeacherFakeId = 9,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 15,  TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 16,  TeacherFakeId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 1,    LectureFakeId = 18,  TeacherFakeId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 1,   TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 3,   TeacherFakeId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 5,   TeacherFakeId = 14,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 7,   TeacherFakeId = 7,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 9,   TeacherFakeId = 9,     WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 10,  TeacherFakeId = 2,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 11,  TeacherFakeId = 10,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 12,  TeacherFakeId = 7,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 14,  TeacherFakeId = 9,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 16,  TeacherFakeId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 19,  TeacherFakeId = 14,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 2,    LectureFakeId = 18,  TeacherFakeId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 1,   TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 3,   TeacherFakeId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 5,   TeacherFakeId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 7,   TeacherFakeId = 18,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 9,   TeacherFakeId = 19,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 10,  TeacherFakeId = 13,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 11,  TeacherFakeId = 16,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 12,  TeacherFakeId = 18,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 14,  TeacherFakeId = 19,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 16,  TeacherFakeId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 19,  TeacherFakeId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 3,    LectureFakeId = 18,  TeacherFakeId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 1,   TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 3,   TeacherFakeId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 5,   TeacherFakeId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 7,   TeacherFakeId = 18,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 9,   TeacherFakeId = 19,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 10,  TeacherFakeId = 17,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 11,  TeacherFakeId = 16,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 12,  TeacherFakeId = 18,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 14,  TeacherFakeId = 19,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 16,  TeacherFakeId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 19,  TeacherFakeId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 4,    LectureFakeId = 18,  TeacherFakeId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 1,   TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 3,   TeacherFakeId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 5,   TeacherFakeId = 5,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 7,   TeacherFakeId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 9,   TeacherFakeId = 21,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 10,  TeacherFakeId = 21,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 11,  TeacherFakeId = 10,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 12,  TeacherFakeId = 20,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 14,  TeacherFakeId = 21,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 16,  TeacherFakeId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 19,  TeacherFakeId = 5,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 5,    LectureFakeId = 18,  TeacherFakeId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 3,   TeacherFakeId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 5,   TeacherFakeId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 7,   TeacherFakeId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 9,   TeacherFakeId = 24,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 10,  TeacherFakeId = 25,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 21,  TeacherFakeId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 15,  TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 6,    LectureFakeId = 18,  TeacherFakeId = 25,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 3,   TeacherFakeId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 5,   TeacherFakeId = 5,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 7,   TeacherFakeId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 9,   TeacherFakeId = 24,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 10,  TeacherFakeId = 20,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 22,  TeacherFakeId = 26,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 21,  TeacherFakeId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 7,    LectureFakeId = 18,  TeacherFakeId = 25,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 3,   TeacherFakeId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 5,   TeacherFakeId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 7,   TeacherFakeId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 9,   TeacherFakeId = 19,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 10,  TeacherFakeId = 12,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 22,  TeacherFakeId = 26,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 21,  TeacherFakeId = 19,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 8,    LectureFakeId = 18,  TeacherFakeId = 25,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 3,   TeacherFakeId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 5,   TeacherFakeId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 7,   TeacherFakeId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 9,   TeacherFakeId = 21,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 10,  TeacherFakeId = 23,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 22,  TeacherFakeId = 26,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 21,  TeacherFakeId = 21,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 9,    LectureFakeId = 18,  TeacherFakeId = 25,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 3,   TeacherFakeId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 4,   TeacherFakeId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 5,   TeacherFakeId = 14,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 6,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 7,   TeacherFakeId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 9,   TeacherFakeId = 27,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 10,  TeacherFakeId = 24,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 22,  TeacherFakeId = 26,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 21,  TeacherFakeId = 27,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 17,  TeacherFakeId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 10,   LectureFakeId = 18,  TeacherFakeId = 28,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 5,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 7,   TeacherFakeId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 10,  TeacherFakeId = 31,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 5,   TeacherFakeId = 5,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 9,   TeacherFakeId = 9,     WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 17,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 11,   LectureFakeId = 18,  TeacherFakeId = 31,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 5,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 7,   TeacherFakeId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 10,  TeacherFakeId = 8,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 5,   TeacherFakeId = 17,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 9,   TeacherFakeId = 34,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 17,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 12,   LectureFakeId = 18,  TeacherFakeId = 31,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 5,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 7,   TeacherFakeId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 10,  TeacherFakeId = 33,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 5,   TeacherFakeId = 14,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 9,   TeacherFakeId = 35,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 17,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 13,   LectureFakeId = 18,  TeacherFakeId = 31,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 1,   TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 5,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 7,   TeacherFakeId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 10,  TeacherFakeId = 29,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 5,   TeacherFakeId = 17,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 9,   TeacherFakeId = 36,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 17,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 14,   LectureFakeId = 18,  TeacherFakeId = 31,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 1,   TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 5,   TeacherFakeId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 7,   TeacherFakeId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 10,  TeacherFakeId = 15,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 2,   TeacherFakeId = 2,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 5,   TeacherFakeId = 14,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 9,   TeacherFakeId = 35,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 17,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 15,   LectureFakeId = 18,  TeacherFakeId = 37,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 1,   TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 5,   TeacherFakeId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 7,   TeacherFakeId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 10,  TeacherFakeId = 10,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 3,   TeacherFakeId = 10,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 9,   TeacherFakeId = 34,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 23,  TeacherFakeId = 34,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 24,  TeacherFakeId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 18,  TeacherFakeId = 38,    WeeklyHourCount = 3 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 25,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 17,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 16,   LectureFakeId = 18,  TeacherFakeId = 38,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 1,   TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 5,   TeacherFakeId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 7,   TeacherFakeId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 10,  TeacherFakeId = 32,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 3,   TeacherFakeId = 10,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 9,   TeacherFakeId = 21,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 23,  TeacherFakeId = 21,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 24,  TeacherFakeId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 18,  TeacherFakeId = 28,    WeeklyHourCount = 3 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 25,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 17,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 17,   LectureFakeId = 18,  TeacherFakeId = 28,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 1,   TeacherFakeId = 40,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 20,  TeacherFakeId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 5,   TeacherFakeId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 7,   TeacherFakeId = 18,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 10,  TeacherFakeId = 18,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 3,   TeacherFakeId = 10,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 7,   TeacherFakeId = 18,    WeeklyHourCount = 12 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 26,  TeacherFakeId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 17,  TeacherFakeId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 18,   LectureFakeId = 18,  TeacherFakeId = 37,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 35,   TeacherFakeId = 1,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 34,  TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 7,   TeacherFakeId = 36,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 10,  TeacherFakeId = 36,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 5,   TeacherFakeId = 14,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 9,   TeacherFakeId = 36,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 27,  TeacherFakeId = 40,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 28,  TeacherFakeId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 18,  TeacherFakeId = 28,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 19,   LectureFakeId = 29,  TeacherFakeId = 41,    WeeklyHourCount = 2 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 35,  TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 34,  TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 7,   TeacherFakeId = 27,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 10,  TeacherFakeId = 16,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 5,   TeacherFakeId = 14,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 8,   TeacherFakeId = 15,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 9,   TeacherFakeId = 27,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 27,  TeacherFakeId = 40,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 28,  TeacherFakeId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 18,  TeacherFakeId = 38,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 20,   LectureFakeId = 29,  TeacherFakeId = 41,    WeeklyHourCount = 2 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 35,  TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 34,  TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 7,   TeacherFakeId = 35,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 10,  TeacherFakeId = 35,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 5,   TeacherFakeId = 5,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 9,   TeacherFakeId = 35,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 27,  TeacherFakeId = 42,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 28,  TeacherFakeId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 18,  TeacherFakeId = 37,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 21,   LectureFakeId = 29,  TeacherFakeId = 41,    WeeklyHourCount = 2 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 35,  TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 34,  TeacherFakeId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 7,   TeacherFakeId = 36,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 10,  TeacherFakeId = 5,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 2,   TeacherFakeId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 5,   TeacherFakeId = 5,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 8,   TeacherFakeId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 9,   TeacherFakeId = 36,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 27,  TeacherFakeId = 42,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 28,  TeacherFakeId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 18,  TeacherFakeId = 37,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 22,   LectureFakeId = 29,  TeacherFakeId = 32,    WeeklyHourCount = 2 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 35,  TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 30,  TeacherFakeId = 41,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 34,  TeacherFakeId = 30,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 7,   TeacherFakeId = 3,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 10,  TeacherFakeId = 27,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 3,   TeacherFakeId = 3,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 31,  TeacherFakeId = 27,    WeeklyHourCount = 8 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 32,  TeacherFakeId = 40,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 23,   LectureFakeId = 18,  TeacherFakeId = 28,    WeeklyHourCount = 8 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 13,  TeacherFakeId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 35,  TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 30,  TeacherFakeId = 41,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 34,  TeacherFakeId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 7,   TeacherFakeId = 22,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 10,  TeacherFakeId = 34,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 3,   TeacherFakeId = 3,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 9,   TeacherFakeId = 34,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 31,  TeacherFakeId = 34,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 32,  TeacherFakeId = 40,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 18,  TeacherFakeId = 38,    WeeklyHourCount = 3 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 24,   LectureFakeId = 18,  TeacherFakeId = 38,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 13,  TeacherFakeId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 1,   TeacherFakeId = 40,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 4,   TeacherFakeId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 6,   TeacherFakeId = 40,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 7,   TeacherFakeId = 7,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 10,  TeacherFakeId = 7,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 3,   TeacherFakeId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 33,  TeacherFakeId = 41,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 7,   TeacherFakeId = 7,     WeeklyHourCount = 12 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 27,  TeacherFakeId = 41,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 26,  TeacherFakeId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 28,  TeacherFakeId = 3,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 18,  TeacherFakeId = 37,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionFakeId = 25,   LectureFakeId = 29,  TeacherFakeId = 41,    WeeklyHourCount = 2 },
    //};

}
