using Planora.Domain.Entities;

namespace Planora.Persistence.SeedData;

public static class SeedTestData
{
    public static List<School> SetSeedDataSchool() => new List<School>
    {
        new School { Name = "Osman İlköğretim" }
    };
    public static List<SchoolScheduleSetting> SetSeedDataSchoolchoolScheduleSetting() => new List<SchoolScheduleSetting>
    {
        new SchoolScheduleSetting {FirstLessonStartTime = TimeSpan.Parse("07:00:00"), LessonDurationMinutes = 40, BreakDurationMinutes = 15, DailyLessonCount = 8 , WeeklyLessonDayCount=5}
    };
    public static List<ClassSection> SetSeedDataClassSection() => new List<ClassSection>
    {
        new ClassSection{FakeId=1,  Name="9-A"},
        new ClassSection{FakeId=2,  Name="9-B"},
        new ClassSection{FakeId=3,  Name="9-C"},
        new ClassSection{FakeId=4,  Name="9-D"},
        new ClassSection{FakeId=5,  Name="9-E"},
        new ClassSection{FakeId=6,  Name="10-A"},
        new ClassSection{FakeId=7,  Name="10-B"},
        new ClassSection{FakeId=8,  Name="10-C"},
        new ClassSection{FakeId=9,  Name="10-D"},
        new ClassSection{FakeId=10, Name="10-E"},
        new ClassSection{FakeId=11, Name="11-A"},
        new ClassSection{FakeId=12, Name="11-B"},
        new ClassSection{FakeId=13, Name="11-C"},
        new ClassSection{FakeId=14, Name="11-D"},
        new ClassSection{FakeId=15, Name="11-E"},
        new ClassSection{FakeId=16, Name="11-F TM"},
        new ClassSection{FakeId=17, Name="11-G TM"},
        new ClassSection{FakeId=18, Name="11-H DİL"},
        new ClassSection{FakeId=19, Name="12-A"},
        new ClassSection{FakeId=20, Name="12-B"},
        new ClassSection{FakeId=21, Name="12-C"},
        new ClassSection{FakeId=22, Name="12-D"},
        new ClassSection{FakeId=23, Name="12-E TM"},
        new ClassSection{FakeId=24, Name="12-F TM"},
        new ClassSection{FakeId=25, Name="12-G DİL"}
    };
    public static List<Teacher> SetSeedDataTeacher() => new List<Teacher>
    {
        new Teacher {FakeId = 1,  FullName = "SEFA ÇOKTU" },
        new Teacher {FakeId = 2,  FullName = "NALAN KARATAŞ" },
        new Teacher {FakeId = 3,  FullName = "YAKUP TURHAN" },
        new Teacher {FakeId = 4,  FullName = "ESRA TEKMİL" },
        new Teacher {FakeId = 5,  FullName = "UĞUR AĞYÜZ" },
        new Teacher {FakeId = 6,  FullName = "ELA ÇAĞLAYAN" },
        new Teacher {FakeId = 7,  FullName = "ÖZLEM ÇOBANOĞLU" },
        new Teacher {FakeId = 8,  FullName = "KEREM DÖŞ" },
        new Teacher {FakeId = 9,  FullName = "EMEL GÖKBULUT" },
        new Teacher {FakeId = 10, FullName = "MEHMET ARKIN" },
        new Teacher {FakeId = 11, FullName = "GÜLER ULUPINAR" },
        new Teacher {FakeId = 12, FullName = "FİLİZ ERKAN ZORLU" },
        new Teacher {FakeId = 13, FullName = "AYBEN ACUN" },
        new Teacher {FakeId = 14, FullName = "ÜNAL AKTOKA" },
        new Teacher {FakeId = 15, FullName = "NİL CEYHAN KARA" },
        new Teacher {FakeId = 16, FullName = "AHMET FATİH TAŞTAN" },
        new Teacher {FakeId = 17, FullName = "ÇİĞDEM DAŞTAN" },
        new Teacher {FakeId = 18, FullName = "NAME TASLAK" },
        new Teacher {FakeId = 19, FullName = "FATİH İYİGÜN" },
        new Teacher {FakeId = 20, FullName = "TUBA ÜSTÜN" },
        new Teacher {FakeId = 21, FullName = "MERAL AKKUŞ" },
        new Teacher {FakeId = 22, FullName = "MURTAZA OĞUZ" },
        new Teacher {FakeId = 23, FullName = "EMİNE ASLAN" },
        new Teacher {FakeId = 24, FullName = "TUĞÇE AKTAŞ" },
        new Teacher {FakeId = 25, FullName = "SEMA AYDIN SÜRER" },
        new Teacher {FakeId = 26, FullName = "SÜMEYYE PAŞO" },
        new Teacher {FakeId = 27, FullName = "RAMİS AKGÜL" },
        new Teacher {FakeId = 28, FullName = "MEHMET TAHİR ÖKSÜZ" },
        new Teacher {FakeId = 29, FullName = "YASEMİN ÇELİK" },
        new Teacher {FakeId = 30, FullName = "ÖMER FARUK" },
        new Teacher {FakeId = 31, FullName = "GÜLTEN KAYHAN" },
        new Teacher {FakeId = 32, FullName = "MUHAMMET SÜHEYL CANSIZ" },
        new Teacher {FakeId = 33, FullName = "SİNEM KANSU" },
        new Teacher {FakeId = 34, FullName = "BURCU ACAR" },
        new Teacher {FakeId = 35, FullName = "MÜSTECEP ŞAHİN" },
        new Teacher {FakeId = 36, FullName = "ÖZCAN ESER" },
        new Teacher {FakeId = 37, FullName = "İBRAHİM FATİH" },
        new Teacher {FakeId = 38, FullName = "AKIN ZORLU" },
        new Teacher {FakeId = 39, FullName = "HALE ŞAHİN" },
        new Teacher {FakeId = 40, FullName = "ERDEM ERBAY" },
        new Teacher {FakeId = 41, FullName = "YASİN KILINÇ" },
        new Teacher {FakeId = 42, FullName = "MUSTAFA DAĞLAR" }
    };
    public static List<Lecture> SetSeedDataLecture() => new List<Lecture>
    {
        new Lecture {FakeId = 1,  Name = "BEDEN EĞİTİMİ VE SPOR" },
        new Lecture {FakeId = 2,  Name = "BİYOLOJİ" },
        new Lecture {FakeId = 3,  Name = "COĞRAFYA" },
        new Lecture {FakeId = 4,  Name = "DİN KÜLTÜRÜ VE AHLAK BİLGİSİ" },
        new Lecture {FakeId = 5,  Name = "FİZİK" },
        new Lecture {FakeId = 6,  Name = "GÖRSEL SANATLAR/MÜZİK" },
        new Lecture {FakeId = 7,  Name = "İNGİLİZCE" },
        new Lecture {FakeId = 8,  Name = "KİMYA" },
        new Lecture {FakeId = 9,  Name = "MATEMATİK" },
        new Lecture {FakeId = 10, Name = "REHBERLİK" },
        new Lecture {FakeId = 11, Name = "SAĞLIK BİLGİSİ VE TRAFİK" },
        new Lecture {FakeId = 12, Name = "ADABI MUAŞERET " },
        new Lecture {FakeId = 13, Name = "ALMANCA" },
        new Lecture {FakeId = 14, Name = "DÜŞÜNME EĞİTİMİ" },
        new Lecture {FakeId = 15, Name = "PEYGAMBERİMİZİN HAYATI" },
        new Lecture {FakeId = 16, Name = "TEMEL DİNİ BİLGİLER" },
        new Lecture {FakeId = 17, Name = "TARİH" },
        new Lecture {FakeId = 18, Name = "TÜRK DİLİ VE EDEBİYATI" },
        new Lecture {FakeId = 19, Name = "ASTRONMİ VE UZAY" },
        new Lecture {FakeId = 20, Name = "FELSEFE" },
        new Lecture {FakeId = 21, Name = "KLS AHLK MET SNT " },
        new Lecture {FakeId = 22, Name = "BİLGİSAYAR BİLİMİ" },
        new Lecture {FakeId = 23, Name = "MATEMATİK UYGULULAMALARI" },
        new Lecture {FakeId = 24, Name = "METİN TAHLİLERİ" },
        new Lecture {FakeId = 25, Name = "TÜRK KÜL.VE MED " },
        new Lecture {FakeId = 26, Name = "TEMEL MATEMATİK" },
        new Lecture {FakeId = 27, Name = " TEMEL HUKUK BİLG" },
        new Lecture {FakeId = 28, Name = "TÜRK SOSYAL HAYT AİLE " },
        new Lecture {FakeId = 29, Name = "T.C. İNKILAP TARİHİ VE ATATÜRK" },
        new Lecture {FakeId = 30, Name = "ÇAĞDAŞ DÜN İNKILAP TARİHİ" },
        new Lecture {FakeId = 31, Name = "MATEMTİK+MAT UYGULAMALARI" },
        new Lecture {FakeId = 32, Name = "SPOR EĞİTİMİ" },
        new Lecture {FakeId = 33, Name = "ÇDŞ TÜRK DNY TARİHİ" },
        new Lecture {FakeId = 34, Name = "GÖRSEL SANATLAR" },
        new Lecture {FakeId = 35, Name = "BEDEN EĞİTİMİ" }
    };

    //public static List<TeacherUnavailable> SetSeedDataTeacherUnavailable() => new List<TeacherUnavailable>
    //{
    //    new TeacherUnavailable {TeacherId = 1, DayOfWeek=1 }
    //};
    //public static List<ClassTeachingAssignment> SetSeedDataClassTeachingAssignment() => new List<ClassTeachingAssignment>
    //{

    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 1,   TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 3,   TeacherId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 5,   TeacherId = 5,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 7,   TeacherId = 7,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 9,   TeacherId = 9,     WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 10,  TeacherId = 9,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 11,  TeacherId = 10,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 12,  TeacherId = 7,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 14,  TeacherId = 9,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 15,  TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 16,  TeacherId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 1,    LectureId = 18,  TeacherId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 1,   TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 3,   TeacherId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 5,   TeacherId = 14,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 7,   TeacherId = 7,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 9,   TeacherId = 9,     WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 10,  TeacherId = 2,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 11,  TeacherId = 10,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 12,  TeacherId = 7,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 14,  TeacherId = 9,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 16,  TeacherId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 19,  TeacherId = 14,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 2,    LectureId = 18,  TeacherId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 1,   TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 3,   TeacherId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 5,   TeacherId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 7,   TeacherId = 18,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 9,   TeacherId = 19,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 10,  TeacherId = 13,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 11,  TeacherId = 16,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 12,  TeacherId = 18,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 14,  TeacherId = 19,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 16,  TeacherId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 19,  TeacherId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 3,    LectureId = 18,  TeacherId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 1,   TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 3,   TeacherId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 5,   TeacherId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 7,   TeacherId = 18,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 9,   TeacherId = 19,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 10,  TeacherId = 17,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 11,  TeacherId = 16,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 12,  TeacherId = 18,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 14,  TeacherId = 19,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 16,  TeacherId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 19,  TeacherId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 4,    LectureId = 18,  TeacherId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 1,   TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 3,   TeacherId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 5,   TeacherId = 5,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 7,   TeacherId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 9,   TeacherId = 21,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 10,  TeacherId = 21,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 11,  TeacherId = 10,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 12,  TeacherId = 20,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 14,  TeacherId = 21,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 16,  TeacherId = 4,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 19,  TeacherId = 5,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 5,    LectureId = 18,  TeacherId = 13,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 3,   TeacherId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 5,   TeacherId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 7,   TeacherId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 9,   TeacherId = 24,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 10,  TeacherId = 25,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 21,  TeacherId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 15,  TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 6,    LectureId = 18,  TeacherId = 25,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 3,   TeacherId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 5,   TeacherId = 5,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 7,   TeacherId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 9,   TeacherId = 24,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 10,  TeacherId = 20,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 22,  TeacherId = 26,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 21,  TeacherId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 7,    LectureId = 18,  TeacherId = 25,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 3,   TeacherId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 5,   TeacherId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 7,   TeacherId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 9,   TeacherId = 19,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 10,  TeacherId = 12,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 22,  TeacherId = 26,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 21,  TeacherId = 19,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 8,    LectureId = 18,  TeacherId = 25,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 3,   TeacherId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 5,   TeacherId = 17,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 7,   TeacherId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 9,   TeacherId = 21,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 10,  TeacherId = 23,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 22,  TeacherId = 26,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 21,  TeacherId = 21,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 9,    LectureId = 18,  TeacherId = 25,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 3,   TeacherId = 10,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 4,   TeacherId = 4,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 5,   TeacherId = 14,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 6,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 7,   TeacherId = 20,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 9,   TeacherId = 27,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 10,  TeacherId = 24,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 22,  TeacherId = 26,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 21,  TeacherId = 27,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 17,  TeacherId = 12,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 10,   LectureId = 18,  TeacherId = 28,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 5,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 7,   TeacherId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 10,  TeacherId = 31,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 5,   TeacherId = 5,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 9,   TeacherId = 9,     WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 17,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 11,   LectureId = 18,  TeacherId = 31,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 5,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 7,   TeacherId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 10,  TeacherId = 8,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 5,   TeacherId = 17,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 9,   TeacherId = 34,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 17,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 12,   LectureId = 18,  TeacherId = 31,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 5,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 7,   TeacherId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 10,  TeacherId = 33,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 5,   TeacherId = 14,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 9,   TeacherId = 35,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 17,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 13,   LectureId = 18,  TeacherId = 31,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 1,   TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 5,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 7,   TeacherId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 10,  TeacherId = 29,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 5,   TeacherId = 17,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 9,   TeacherId = 36,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 17,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 14,   LectureId = 18,  TeacherId = 31,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 1,   TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 5,   TeacherId = 6,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 7,   TeacherId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 10,  TeacherId = 15,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 2,   TeacherId = 2,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 5,   TeacherId = 14,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 9,   TeacherId = 35,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 17,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 15,   LectureId = 18,  TeacherId = 37,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 1,   TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 5,   TeacherId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 7,   TeacherId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 10,  TeacherId = 10,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 3,   TeacherId = 10,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 9,   TeacherId = 34,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 23,  TeacherId = 34,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 24,  TeacherId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 18,  TeacherId = 38,    WeeklyHourCount = 3 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 25,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 17,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 16,   LectureId = 18,  TeacherId = 38,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 1,   TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 5,   TeacherId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 7,   TeacherId = 30,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 10,  TeacherId = 32,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 3,   TeacherId = 10,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 9,   TeacherId = 21,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 23,  TeacherId = 21,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 24,  TeacherId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 18,  TeacherId = 28,    WeeklyHourCount = 3 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 25,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 17,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 17,   LectureId = 18,  TeacherId = 28,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 1,   TeacherId = 40,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 20,  TeacherId = 23,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 5,   TeacherId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 7,   TeacherId = 18,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 10,  TeacherId = 18,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 3,   TeacherId = 10,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 7,   TeacherId = 18,    WeeklyHourCount = 12 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 26,  TeacherId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 17,  TeacherId = 32,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 18,   LectureId = 18,  TeacherId = 37,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 35,   TeacherId = 1,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 34,  TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 7,   TeacherId = 36,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 10,  TeacherId = 36,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 5,   TeacherId = 14,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 9,   TeacherId = 36,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 27,  TeacherId = 40,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 28,  TeacherId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 18,  TeacherId = 28,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionId = 19,   LectureId = 29,  TeacherId = 41,    WeeklyHourCount = 2 },

    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 35,  TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 34,  TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 7,   TeacherId = 27,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 10,  TeacherId = 16,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 5,   TeacherId = 14,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 8,   TeacherId = 15,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 9,   TeacherId = 27,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 27,  TeacherId = 40,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 28,  TeacherId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 18,  TeacherId = 38,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionId = 20,   LectureId = 29,  TeacherId = 41,    WeeklyHourCount = 2 },

    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 35,  TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 34,  TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 7,   TeacherId = 35,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 10,  TeacherId = 35,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 5,   TeacherId = 5,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 9,   TeacherId = 35,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 27,  TeacherId = 42,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 28,  TeacherId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 18,  TeacherId = 37,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionId = 21,   LectureId = 29,  TeacherId = 41,    WeeklyHourCount = 2 },

    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 35,  TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 34,  TeacherId = 22,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 7,   TeacherId = 36,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 10,  TeacherId = 5,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 2,   TeacherId = 16,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 5,   TeacherId = 5,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 8,   TeacherId = 8,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 9,   TeacherId = 36,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 27,  TeacherId = 42,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 28,  TeacherId = 39,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 18,  TeacherId = 37,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionId = 22,   LectureId = 29,  TeacherId = 32,    WeeklyHourCount = 2 },

    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 35,  TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 30,  TeacherId = 41,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 34,  TeacherId = 30,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 7,   TeacherId = 3,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 10,  TeacherId = 27,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 3,   TeacherId = 3,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 31,  TeacherId = 27,    WeeklyHourCount = 8 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 32,  TeacherId = 40,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 23,   LectureId = 18,  TeacherId = 28,    WeeklyHourCount = 8 },

    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 13,  TeacherId = 33,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 35,  TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 30,  TeacherId = 41,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 34,  TeacherId = 1,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 7,   TeacherId = 22,    WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 10,  TeacherId = 34,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 3,   TeacherId = 3,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 9,   TeacherId = 34,    WeeklyHourCount = 6 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 31,  TeacherId = 34,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 32,  TeacherId = 40,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 18,  TeacherId = 38,    WeeklyHourCount = 3 },
    //    new ClassTeachingAssignment { ClassSectionId = 24,   LectureId = 18,  TeacherId = 38,    WeeklyHourCount = 5 },

    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 13,  TeacherId = 11,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 1,   TeacherId = 40,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 4,   TeacherId = 29,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 6,   TeacherId = 40,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 7,   TeacherId = 7,     WeeklyHourCount = 4 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 10,  TeacherId = 7,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 3,   TeacherId = 3,     WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 33,  TeacherId = 41,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 7,   TeacherId = 7,     WeeklyHourCount = 12 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 27,  TeacherId = 41,    WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 26,  TeacherId = 24,    WeeklyHourCount = 2 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 28,  TeacherId = 3,     WeeklyHourCount = 1 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 18,  TeacherId = 37,    WeeklyHourCount = 5 },
    //    new ClassTeachingAssignment { ClassSectionId = 25,   LectureId = 29,  TeacherId = 41,    WeeklyHourCount = 2 },
    //};
}
